select * from project limit 10;

--Q1. What is the total revenue generated by male vs. female customers?
SELECT GENDER,
	SUM(PURCHASE_AMOUNT) AS TOTAL_REVENUE
FROM PROJECT
GROUP BY GENDER

--Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT CUSTOMER_ID,
	PURCHASE_AMOUNT
FROM PROJECT
WHERE DISCOUNT_APPLIED = 'Yes'
	AND PURCHASE_AMOUNT >=
		(SELECT AVG(PURCHASE_AMOUNT)
			FROM PROJECT)
			
-- Q3. Which are the top 5 products with the highest average review rating?
SELECT ITEM_PURCHASED,
	ROUND(AVG(REVIEW_RATING::numeric),2) AS AVG_RATING
FROM PROJECT
GROUP BY ITEM_PURCHASED
ORDER BY AVG(REVIEW_RATING) DESC
LIMIT 5;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
SELECT SHIPPING_TYPE,
	ROUND(AVG(PURCHASE_AMOUNT),2)
FROM PROJECT
WHERE SHIPPING_TYPE IN ('Standard','Express')
GROUP BY SHIPPING_TYPE

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
SELECT SUBSCRIPTION_STATUS,
	COUNT(CUSTOMER_ID) AS TOTAL_CUSTOMER,
	ROUND(AVG(PURCHASE_AMOUNT),2) AS AVG_PURCHASEAMT,
	SUM(PURCHASE_AMOUNT) AS TOTAL_REVENUE
FROM PROJECT
GROUP BY SUBSCRIPTION_STATUS;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*), 2) AS discount_rate
FROM project
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 

WITH CUSTOMER_TYPE AS
	(SELECT CUSTOMER_ID,PREVIOUS_PURCHASES,
		CASE
			WHEN PREVIOUS_PURCHASES = 1 THEN 'New Customer'
			WHEN PREVIOUS_PURCHASES BETWEEN 2 AND 10 THEN 'Returning'
			WHEN PREVIOUS_PURCHASES > 10 THEN 'Loyal Customer'
			END AS CUSTOMER_SEGMENT
		FROM PROJECT)
SELECT CUSTOMER_SEGMENT,COUNT(*) AS "No of customers"
FROM CUSTOMER_TYPE
GROUP BY CUSTOMER_SEGMENT

--Q8. What are the top 3 most purchased products within each category? 
WITH ITEM_COUNTS AS
	(SELECT CATEGORY,ITEM_PURCHASED,
		COUNT(CUSTOMER_ID) AS TOTAL_ORDERS,
		ROW_NUMBER() OVER(PARTITION BY CATEGORY ORDER BY COUNT(CUSTOMER_ID) DESC) 
	 	AS ITEM_RANKFROM PROJECT
		GROUP BY CATEGORY,ITEM_PURCHASED)
SELECT ITEM_RANK,CATEGORY,ITEM_PURCHASED,TOTAL_ORDERS
FROM ITEM_COUNTS
WHERE ITEM_RANK <= 3;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT SUBSCRIPTION_STATUS,
	COUNT(CUSTOMER_ID) AS REPEAT_BUYERS
FROM PROJECT
WHERE PREVIOUS_PURCHASES > 5
GROUP BY SUBSCRIPTION_STATUS

--Q10. What is the revenue contribution of each age group? 
SELECT AGE_GROUP,
	SUM(PURCHASE_AMOUNT) AS TOTAL_REVENUE
FROM PROJECT
GROUP BY AGE_GROUP
ORDER BY TOTAL_REVENUE DESC


